


services:   # Это основной раздел в нем должен присутствовать хотя бы один сервис
  app:  # тут может быть сервис postgress или fastapi 
    build: .   # точка указывает что докер файл находится в каталоге\директории 

